// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20210619122024_add")]
    partial class add
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mansoura"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alexandria"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Luxor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Asyut"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tanta"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Luxor"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cairo"
                        });
                });

            modelBuilder.Entity("Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Data.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("orderItems");
                });

            modelBuilder.Entity("Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Product1",
                            Name = "Product1",
                            Price = 10.0,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Product2",
                            Name = "Product2",
                            Price = 14.0,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Product3",
                            Name = "Product3",
                            Price = 12.0,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Product1",
                            Name = "Product1",
                            Price = 22.0,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Product2",
                            Name = "Product2",
                            Price = 43.0,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Product3",
                            Name = "Product3",
                            Price = 21.0,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Product1",
                            Name = "Product1",
                            Price = 54.0,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 8,
                            Description = "Product2",
                            Name = "Product2",
                            Price = 22.0,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "Product3",
                            Name = "Product3",
                            Price = 31.0,
                            RestaurantId = 3
                        });
                });

            modelBuilder.Entity("Data.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 6,
                            Description = "Abou El Sid is the must-go-to restaurant if you want classic Egyptian dishes (check out our article 12 Local Egyptian Foods You Need To Try) in a super ambient atmosphere (the decor, music, and wall art is enough to make it worth it). They also offer shisha and Egyptian twists on alcoholic cocktails, like vodka with fresh sugarcane juice.",
                            Name = "Koshary Abou Tarek"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "Abou El Sid is the must-go-to restaurant if you want classic Egyptian dishes (check out our article 12 Local Egyptian Foods You Need To Try) in a super ambient atmosphere (the decor, music, and wall art is enough to make it worth it). They also offer shisha and Egyptian twists on alcoholic cocktails, like vodka with fresh sugarcane juice.",
                            Name = "Bremer"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "Abou El Sid is the must-go-to restaurant if you want classic Egyptian dishes (check out our article 12 Local Egyptian Foods You Need To Try) in a super ambient atmosphere (the decor, music, and wall art is enough to make it worth it). They also offer shisha and Egyptian twists on alcoholic cocktails, like vodka with fresh sugarcane juice.",
                            Name = "Smoven restaurant"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            Description = "Abou El Sid is the must-go-to restaurant if you want classic Egyptian dishes (check out our article 12 Local Egyptian Foods You Need To Try) in a super ambient atmosphere (the decor, music, and wall art is enough to make it worth it). They also offer shisha and Egyptian twists on alcoholic cocktails, like vodka with fresh sugarcane juice.",
                            Name = "Cafe Supreme"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 4,
                            Description = "Abou El Sid is the must-go-to restaurant if you want classic Egyptian dishes (check out our article 12 Local Egyptian Foods You Need To Try) in a super ambient atmosphere (the decor, music, and wall art is enough to make it worth it). They also offer shisha and Egyptian twists on alcoholic cocktails, like vodka with fresh sugarcane juice.",
                            Name = "Oriental Grill"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 6,
                            Description = "Abou El Sid is the must-go-to restaurant if you want classic Egyptian dishes (check out our article 12 Local Egyptian Foods You Need To Try) in a super ambient atmosphere (the decor, music, and wall art is enough to make it worth it). They also offer shisha and Egyptian twists on alcoholic cocktails, like vodka with fresh sugarcane juice.",
                            Name = "Shashlik"
                        });
                });

            modelBuilder.Entity("Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Data.Models.Order", b =>
                {
                    b.HasOne("Data.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Models.OrderItem", b =>
                {
                    b.HasOne("Data.Models.Order", "Order")
                        .WithMany("orderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Data.Models.Product", b =>
                {
                    b.HasOne("Data.Models.Restaurant", "Restaurant")
                        .WithMany("ProductList")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Data.Models.Restaurant", b =>
                {
                    b.HasOne("Data.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Data.Models.Order", b =>
                {
                    b.Navigation("orderItems");
                });

            modelBuilder.Entity("Data.Models.Restaurant", b =>
                {
                    b.Navigation("ProductList");
                });

            modelBuilder.Entity("Data.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
